# Generated by Django 4.2.5 on 2023-10-13 00:54

from django.contrib.postgres.operations import BtreeGinExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0004_conversationprocessorconfig_githubconfig_and_more"),
    ]

    operations = [
        BtreeGinExtension(),
    ]
