# Generated by Django 4.2.5 on 2023-09-27 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0002_googleuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="Configuration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
        ),
        migrations.CreateModel(
            name="ConversationProcessorConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("conversation", models.JSONField()),
                ("enable_offline_chat", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="GithubConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("pat_token", models.CharField(max_length=200)),
                ("compressed_jsonl", models.CharField(max_length=300)),
                ("embeddings_file", models.CharField(max_length=300)),
                (
                    "config",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="database.configuration"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="khojuser",
            name="uuid",
            field=models.UUIDField(verbose_name=models.UUIDField(default=uuid.uuid4, editable=False)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="NotionConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token", models.CharField(max_length=200)),
                ("compressed_jsonl", models.CharField(max_length=300)),
                ("embeddings_file", models.CharField(max_length=300)),
                (
                    "config",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="database.configuration"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GithubRepoConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("owner", models.CharField(max_length=200)),
                ("branch", models.CharField(max_length=200)),
                (
                    "github_config",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="database.githubconfig"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="configuration",
            name="user",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
