# Generated by Django 4.2.5 on 2023-10-08 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0004_khojconfig_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="githubrepoconfig",
            name="github_config",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="githubrepoconfig", to="database.githubconfig"
            ),
        ),
        migrations.AlterField(
            model_name="localorgconfig",
            name="input_files",
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name="localorgconfig",
            name="input_filter",
            field=models.JSONField(default=list, null=True),
        ),
    ]
