# Generated by Django 4.2.5 on 2023-10-04 15:55

from django.db import migrations, models
import pgvector.django


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0005_embeddings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="embeddings",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("image", "Image"),
                    ("pdf", "Pdf"),
                    ("plaintext", "Plaintext"),
                    ("markdown", "Markdown"),
                    ("org", "Org"),
                    ("notion", "Notion"),
                    ("github", "Github"),
                    ("conversation", "Conversation"),
                ],
                default="plaintext",
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="embeddings",
            index=pgvector.django.IvfflatIndex(
                fields=["embeddings"], lists=256, name="embeddings_idx", opclasses=["vector_cosine_ops"]
            ),
        ),
    ]
