# Generated by Django 4.2.5 on 2023-10-13 02:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("database", "00005_btree_gin_ext"),
    ]

    operations = [
        migrations.AddField(
            model_name="embeddings",
            name="corpus_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
