# Generated by Django 4.2.5 on 2023-10-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0005_alter_githubrepoconfig_github_config_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="localmarkdownconfig",
            name="input_files",
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name="localmarkdownconfig",
            name="input_filter",
            field=models.JSONField(default=list, null=True),
        ),
    ]
