# Generated by Django 4.2.5 on 2023-10-16 16:29

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0006_embeddingsdates"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="embeddings",
            index=pgvector.django.HnswIndex(
                ef_construction=64, fields=["embeddings"], m=16, name="embeddings_idx", opclasses=["vector_cosine_ops"]
            ),
        ),
    ]
