# Generated by Django 4.2.5 on 2023-10-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0007_alter_localpdfconfig_input_files_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="embeddings",
            name="heading",
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
