# Generated by Django 4.2.5 on 2023-10-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0007_alter_embeddings_file_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="embeddings",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("image", "Image"),
                    ("pdf", "Pdf"),
                    ("plaintext", "Plaintext"),
                    ("markdown", "Markdown"),
                    ("org", "Org"),
                    ("notion", "Notion"),
                    ("github", "Github"),
                    ("conversation", "Conversation"),
                ],
                default="plaintext",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="embeddings",
            name="raw",
            field=models.CharField(max_length=2000),
        ),
    ]
