# Generated by Django 4.2.5 on 2023-10-05 00:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0011_remove_embeddings_embeddings_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="embeddings",
            name="embeddings_idx",
        ),
        migrations.AlterField(
            model_name="embeddings",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("image", "Image"),
                    ("pdf", "Pdf"),
                    ("plaintext", "Plaintext"),
                    ("markdown", "Markdown"),
                    ("org", "Org"),
                    ("notion", "Notion"),
                    ("github", "Github"),
                    ("conversation", "Conversation"),
                ],
                default="plaintext",
                max_length=30,
            ),
        ),
    ]
