# Generated by Django 4.2.5 on 2023-11-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0012_entry_file_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="khojuser",
            name="subscription_renewal_date",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="khojuser",
            name="subscription_type",
            field=models.CharField(
                choices=[("trial", "Trial"), ("standard", "Standard")], default="trial", max_length=20
            ),
        ),
    ]
