# Generated by Django 4.2.5 on 2023-11-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0013_khojuser_subscription_renewal_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="khojuser",
            name="is_subscribed",
            field=models.BooleanField(default=False),
        ),
    ]
