# Generated by Django 4.2.10 on 2024-04-26 16:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0036_alter_processlock_name"),
        ("database", "0037_searchmodelconfig_bi_encoder_docs_encode_config_and_more"),
    ]

    operations: list = []
