# Generated by Django 4.2.7 on 2023-11-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0019_alter_googleuser_family_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpeechToTextModelOptions",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("model_name", models.CharField(default="whisper-1", max_length=200)),
                (
                    "model_type",
                    models.CharField(
                        choices=[("openai", "Openai"), ("offline", "Offline")], default="openai", max_length=200
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="chatmodeloptions",
            name="chat_model",
            field=models.CharField(default="gpt-4", max_length=200),
        ),
    ]
