# Generated by Django 4.2.7 on 2023-11-26 06:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0020_reflectivequestion"),
        ("database", "0020_speechtotextmodeloptions_and_more"),
    ]

    operations: list = []
