# Generated by Django 4.2.7 on 2024-02-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0030_conversation_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="title",
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
