# Generated by Django 4.2.10 on 2024-03-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0030_conversation_slug_and_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="googleuser",
            name="locale",
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
