# Generated by Django 4.2.10 on 2024-04-29 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0041_merge_20240505_1234"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServerChatSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "default_model",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="default_model",
                        to="database.chatmodeloptions",
                    ),
                ),
                (
                    "summarizer_model",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summarizer_model",
                        to="database.chatmodeloptions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
