# Generated by Django 4.2.11 on 2024-06-06 22:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0043_alter_chatmodeloptions_model_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("image", "Image"),
                    ("pdf", "Pdf"),
                    ("plaintext", "Plaintext"),
                    ("markdown", "Markdown"),
                    ("org", "Org"),
                    ("notion", "Notion"),
                    ("github", "Github"),
                    ("conversation", "Conversation"),
                    ("docx", "Docx"),
                ],
                default="plaintext",
                max_length=30,
            ),
        ),
    ]
