# Generated by Django 4.2.10 on 2024-06-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0043_alter_chatmodeloptions_model_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileObject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file_name", models.CharField(blank=True, default=None, max_length=400, null=True)),
                ("raw_text", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="conversation",
            name="file_filters",
            field=models.JSONField(default=list),
        ),
    ]
