# Generated by Django 4.2.11 on 2024-06-07 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0044_fileobject_conversation_file_filters"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileobject",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
