# Generated by Django 5.0.8 on 2024-09-16 04:12

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0062_merge_20240913_0222"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="unique_id",
            field=models.UUIDField(default=None, editable=False, null=True),
        ),
    ]
