# Generated by Django 5.0.8 on 2024-10-01 00:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0065_remove_agent_avatar_remove_agent_public_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agent",
            name="tools",
        ),
        migrations.AddField(
            model_name="agent",
            name="input_tools",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("general", "General"),
                        ("online", "Online"),
                        ("notes", "Notes"),
                        ("summarize", "Summarize"),
                        ("webpage", "Webpage"),
                    ],
                    max_length=200,
                ),
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="output_modes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(choices=[("text", "Text"), ("image", "Image")], max_length=200),
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="style_icon",
            field=models.CharField(
                choices=[
                    ("Lightbulb", "Lightbulb"),
                    ("Health", "Health"),
                    ("Robot", "Robot"),
                    ("Aperture", "Aperture"),
                    ("GraduationCap", "Graduation Cap"),
                    ("Jeep", "Jeep"),
                    ("Island", "Island"),
                    ("MathOperations", "Math Operations"),
                    ("Asclepius", "Asclepius"),
                    ("Couch", "Couch"),
                    ("Code", "Code"),
                    ("Atom", "Atom"),
                    ("ClockCounterClockwise", "Clock Counter Clockwise"),
                    ("PencilLine", "Pencil Line"),
                    ("Chalkboard", "Chalkboard"),
                ],
                default="Lightbulb",
                max_length=200,
            ),
        ),
    ]
