# Generated by Django 5.0.8 on 2024-10-16 00:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0067_alter_agent_style_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="serverchatsettings",
            name="web_scraper",
            field=models.CharField(
                choices=[("firecrawl", "Firecrawl"), ("olostep", "Olostep"), ("jinaai", "JinaAI")],
                default="jinaai",
                max_length=20,
            ),
        ),
    ]
