# Generated by Django 5.0.8 on 2024-10-21 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0071_subscription_enabled_trial_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="search_model",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="database.searchmodelconfig",
            ),
        ),
    ]
