# Generated by Django 5.0.9 on 2024-12-04 05:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0074_alter_conversation_title"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OpenAIProcessorConversationConfig",
            new_name="ChatApiProvider",
        ),
        migrations.RenameField(
            model_name="chatmodeloptions",
            old_name="openai_config",
            new_name="chat_api_provider",
        ),
    ]
