# Generated by Django 5.0.10 on 2024-12-23 01:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0078_khojuser_email_verification_code_expiry"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="named_entities",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
