# Generated by Django 5.0.13 on 2025-04-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0087_alter_aimodelapi_api_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmodel",
            name="price_tier",
            field=models.CharField(choices=[("free", "Free"), ("standard", "Standard")], default="free", max_length=20),
        ),
        migrations.AddField(
            model_name="speechtotextmodeloptions",
            name="price_tier",
            field=models.CharField(choices=[("free", "Free"), ("standard", "Standard")], default="free", max_length=20),
        ),
        migrations.AddField(
            model_name="texttoimagemodelconfig",
            name="price_tier",
            field=models.CharField(choices=[("free", "Free"), ("standard", "Standard")], default="free", max_length=20),
        ),
        migrations.AddField(
            model_name="voicemodeloption",
            name="price_tier",
            field=models.CharField(
                choices=[("free", "Free"), ("standard", "Standard")], default="standard", max_length=20
            ),
        ),
    ]
