# Generated by Django 5.0.13 on 2025-04-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0087_alter_aimodelapi_api_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="RateLimitRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("identifier", models.CharField(db_index=True, max_length=255)),
                ("slug", models.CharField(db_index=True, max_length=255)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["identifier", "slug", "created_at"], name="database_ra_identif_031adf_idx")
                ],
            },
        ),
    ]
