# Generated by Django 5.1.10 on 2025-07-01 01:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0090_alter_khojuser_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchmodelconfig",
            name="search_diversity_final_limit",
            field=models.IntegerField(default=15, help_text="Final limit on number of diverse results to return"),
        ),
        migrations.AddField(
            model_name="searchmodelconfig",
            name="search_diversity_max_per_file",
            field=models.IntegerField(
                default=3, help_text="Maximum number of results to include per file to promote diversity"
            ),
        ),
        migrations.AddField(
            model_name="searchmodelconfig",
            name="search_diversity_max_results",
            field=models.IntegerField(
                default=25, help_text="Maximum number of results to retrieve before diversity sampling"
            ),
        ),
    ]
