# Generated by Django 5.1.10 on 2025-06-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0091_chatmodel_friendly_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="McpServer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("uri", models.CharField(max_length=1000, unique=True)),
                ("api_key", models.CharField(blank=True, max_length=400, null=True)),
                ("enabled", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
