# Generated by Django 5.1.14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0099_usermemory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="texttoimagemodelconfig",
            name="model_type",
            field=models.CharField(
                choices=[
                    ("openai", "Openai"),
                    ("replicate", "Replicate"),
                    ("google", "Google"),
                    ("modelslab", "Modelslab"),
                ],
                default="openai",
                max_length=200,
            ),
        ),
    ]
