# Generated by Django 5.1.14 on 2026-06-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0099_usermemory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webscraper",
            name="type",
            field=models.CharField(
                choices=[
                    ("Firecrawl", "Firecrawl"),
                    ("Crw", "Crw"),
                    ("Olostep", "Olostep"),
                    ("Exa", "Exa"),
                    ("Direct", "Direct"),
                ],
                default="Direct",
                max_length=20,
            ),
        ),
    ]
